folio-org/ui-service-interaction

src/public/components/NumberGeneratorButton/NumberGeneratorButton.js
src/public/components/NumberGeneratorButton/README.md
src/public/components/NumberGeneratorModal/NumberGeneratorModal.js
src/public/components/NumberGeneratorModal/README.md
src/public/components/NumberGeneratorModal/index.js
src/public/components/NumberGeneratorModalButton/NumberGeneratorModalButton.js
src/public/components/NumberGeneratorModalButton/README.md
src/public/components/index.js
src/public/index.js

Exposed NumberGeneratorModal as a separate component
Also added a way to pass buttonProps down through the various components
Documentation to reflect these changes

feat: NumberGeneratorModal

---

CONTRIBUTING.md
README.md

https://dev.folio.org/guidelines/create-new-repo/

FOLIO-722 initial repo setup required doc

---

package.json
src/settings/NumberGeneratorConfig.js
src/settings/NumberGeneratorSequenceConfig.js
translations/ui-service-interaction/en.json

Settings pages no longer change back to start after editing/creating a value. Also delete no longer appears for a number generator if there are any sequences present.

feat: Settings improvements

---

src/settings/NumberGeneratorSequenceConfig.js
translations/ui-service-interaction/en.json

Added field to settings to apply format to a new number generator

feat: format

---

src/settings/NumberGeneratorSequence.js
src/settings/NumberGeneratorSequenceConfig.js
translations/ui-service-interaction/en.json

Added tooltips to actions (will take effect after release 2.9.0 of kint-comps), added onRowClick (some code added to work backwards compatibly, but can be removed after 2.9.0), also made description field full width in view pane

feat: Accessibility tweaks

---

package.json

Bumped interface dep for servint from 1.0 to 2.0

build: Bump servint interface dep

---

__mocks__/@folio/stripes-components.js
__mocks__/@folio/stripes/core.js
__mocks__/@folio/stripes/smart-components.js
__mocks__/@k-int/stripes-kint-components.js
__mocks__/currency-codes/data.js
__mocks__/react-query.js
__mocks__/react-router-dom.js
__mocks__/stripes-config.js
jest.config.js
package.json
src/public/components/NumberGeneratorButton/NumberGeneratorButton.test.js
src/public/components/NumberGeneratorModalButton/NumberGeneratorModalButton.test.js
test/helpers/translationsProperties.js

Set up ui-service-interaction to use stripes-erm-testing repository instead of stripes-erm-components

test: Setup testing

---

package.json
test/helpers/translationsProperties.js

Added changelog, updated dependencies

chore: Release 1.0.0

---

PERSONAL_DATA_DISCLOSURE.md
README.md

Added PERSONAL_DATA_DISCLOSURE.md and running information to README.md

docs: Acceptance Documentation

---

src/settings/NumberGeneratorConfig.js
translations/ui-service-interaction/en.json

chore: Help banner
Added help banner to Number Generator Settings page
SI-5

SI-5: Add help banner to Number Generator screen

---

src/settings/NumberGeneratorConfig.js
translations/ui-service-interaction/en.json

Minor fixes and tweaks to NUmber Generator Settings page
refs SI-13/SI-14

fix: Minor fixes

---

src/settings/NumberGeneratorSequenceForm.js

fix: Focus
Added autofocus to first field in number generator sequence form modal
SI-17

SI-17: Service interaction > Number generator sequences

---

package.json

Added okapi interface dependency on new servint interface 3.0
refs ERM-2641

build: servint 3.0

---

CHANGELOG.md
package.json
src/public/utilities/ModalButton.test.js

Updated CHANGELOG and dependencies for 2.0.0 release
SI-40

chore: Release 2.0.0

---

package.json
src/settings/NumberGeneratorConfig/NumberGeneratorConfig.js
src/settings/NumberGeneratorSequenceRoute/SequenceSearch.js
src/settings/NumberGeneratorSequenceRoute/SequenceView.js
src/settings/index.js

* Tweaked wording of UI permissions
* Added permission block to viewing settings pages where NumberGenerator view perm is not in place
* Added permission blocks to create/edit/delete in NumberGenerator config ActionList
* Added permission block to create button in NumberGeneratorSequences page
* Added permission block to "Actions" button in NumberGeneratorSequence view pane

feat: SI-43 Permissions changes

---

package.json

chore: Permissions
Added view permission as sub permission to manage perm, in order to streamline user experience
SI-43

SI-43: Permissions for ui service interaction and number generators (fix)

---

src/public/components/NumberGeneratorSelector/index.js
src/public/components/index.js

Accidentally imported default where no default existed, fixed this

fix: Whoops import

---

src/public/hooks/useGenerateNumber/useGenerateNumber.js

The return value for useGenerateNumber generate now contains return values from refetch again

fix: useGenerateNumber return

---

src/settings/NumberGeneratorSequenceRoute/SequenceFilters.js
src/settings/NumberGeneratorSequenceRoute/SequenceFilters.test.js
src/settings/NumberGeneratorSequenceRoute/SequenceSearch.js
translations/ui-service-interaction/en.json

Expand sequence filter options, provide test
SI-4

feat: Sequence Filters

---

src/public/components/NumberGeneratorModal/LegacyNumberGeneratorModal/LegacyNumberGeneratorModal.js
src/public/components/NumberGeneratorSelector/NumberGeneratorSelector.js
src/public/hooks/useGenerateNumber/useGenerateNumber.js

Tweaked code to remove code smells

chore: Code smells

---

src/public/hooks/useGenerateNumber/useGenerateNumber.test.js
src/public/hooks/useMutateNumberGenerator.test.js
src/public/hooks/useMutateNumberGeneratorSequence.test.js
src/public/hooks/useNumberGeneratorSequence.test.js
src/public/hooks/useNumberGeneratorSequences/useNumberGeneratorSequences.js
src/public/hooks/useNumberGeneratorSequences/useNumberGeneratorSequences.test.js

test: Test coverage

---

CHANGELOG.md

Bring changelog in line with changes since release

docs: CHANGELOG update

---

.github/workflows/validate.yml
package.json

ci: Added module validation and tweaked package to reflect backend changes

Package json validation

---

package.json
src/public/hooks/useGenerateNumber/useGenerateNumber.test.js
src/settings/NumberGeneratorSequenceRoute/SequenceSearch.test.js
src/settings/NumberGeneratorSequenceRoute/SequenceView.test.js

Bump erm-testing dep to 3.0.0 and tweak uses of the extraOptions in renderWithIntl to fit the new shape

test: Update stripes-erm-testing dep

---

src/index.test.js
src/public/components/NumberGeneratorButton/NumberGeneratorButton.test.js
src/public/components/NumberGeneratorModal/LegacyNumberGeneratorModal/LegacyNumberGeneratorModal.test.js
src/public/components/NumberGeneratorModal/NumberGeneratorModal.test.js
src/public/components/NumberGeneratorModalButton/NumberGeneratorModalButton.test.js
src/public/components/NumberGeneratorSelector/NumberGeneratorSelector.test.js
src/public/hooks/useGenerateNumber/useGenerateNumber.test.js
src/public/utilities/ModalButton.test.js
src/settings/InfoPopovers/InfoPopovers.test.js
src/settings/NumberGeneratorConfig/NumberGeneratorConfig.test.js
src/settings/NumberGeneratorSequenceRoute/NumberGeneratorSequenceForm.test.js
src/settings/NumberGeneratorSequenceRoute/SequenceFilters.test.js
src/settings/NumberGeneratorSequenceRoute/SequenceSearch.test.js
src/settings/NumberGeneratorSequenceRoute/SequenceView.test.js
src/settings/index.js
src/settings/index.test.js
test/helpers/index.js
test/helpers/renderWithTranslations.js

Tweaked test for settings page to handle different sections. Example of how we might reliably test Settings pages... although its a bit messy

test: Testing Settings page

---

src/public/components/NumberGeneratorSelector/NumberGeneratorSelector.test.js

Refactor NUmberGeneratorSelector test to use .each syntax. Not 100% sure it's any better or worse than it was tbh

refactor: Refactor NUmberGeneratorSelector test

---

src/settings/NumberGeneratorSequenceRoute/NumberGeneratorSequenceForm/NumberGeneratorSequenceForm.js

fix: Added back option for null checksum method, as it can exist in older data

---

src/settings/NumberGeneratorSequenceRoute/SequenceSearch/SequenceSearch.js

Fixed an issue in which the "enabled" checkbox was not true by default, updated initial values on a new sequence
SI-73

SI-73: Modal new sequence/edit sequence display enhancements

---

src/settings/InfoPopovers/InfoPopovers.js

Added "learn more" button to method info popover
SI-75

SI-75: Help text adjustments for modal new sequence/edit sequence and detail pane sequences

---

CHANGELOG.md

Added CHANGELOG section as reflected in 3.1.1 release

chore: Post-release 3.1.1

---

package.json
src/public/components/NumberGeneratorSelector/NumberGeneratorSelector.js
src/public/utilities/ModalButton.js
src/public/utilities/ModalButton.test.js

Also bumped version of stripes-kint-components
Added/fixed typos in comments

fix: removed dismissible from ModalButton as default

---

src/settings/InfoPopovers/InfoPopovers.test.js
translations/ui-service-interaction/en.json
translations/ui-service-interaction/en_US.json

[Escaping ostensibly comes from this standard](https://unicode-org.github.io/icu/userguide/format_parse/messages/#quotingescaping)
To be confirmed

fix: Small tweak to translation file to attempt to escape characters that may be causing issues

---

CHANGELOG.md

Updated CHANGELOG.md section to reflect release changes
SI-110

chore: Release 4.0.0

---

CHANGELOG.md
package.json

Bumped version to 4.1.0 and added CHANGELOG section

chore: Post release 4.0.0
